更新django到3.xLTS，并合并上游依赖的升级，为彻底移除已过时语言依赖做准备
QingdaoU/OnlineJudge pull request #392
Opened 2021-11-18 10:15 UTC by Beichi-CHs

1. django2.x即将停止支持，更新django到3.x LTS，相应地更新了全部相关依赖，处理了兼容性问题
2. 合并底包版本到python3.8-alpine3.14，为移除已过时的python2语言依赖做准备

2021-11-18 13:56 UTC, virusdefender requested changes

2021-11-18 13:56 UTC, virusdefender commented on run_test.py
> +ret = os.system('coverage run --include=\"$PWD/*\" manage.py test {module} --settings={setting}'.format(module=test_module, setting=setting))
这样里面的双引号是不是不需要转义了

2021-11-18 13:56 UTC, virusdefender commented on conf/tests.py
> +        self.assertEqual(SysOptions.website_footer, '<img src=\"#\" />')
这样里面的双引号是不是不需要转义了

2021-12-08 00:24 UTC, virusdefender approved these changes

2021-12-08 00:24 UTC, merged

2021-12-08 00:24 UTC, virusdefender commented
感谢大佬

2021-12-08 00:24 UTC, Doubeecat commented
你好，你发来的邮件已收到。谢谢

2021-12-08 00:24 UTC, AnnYeLi commented
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2021-12-09 08:15 UTC, zhblue commented
恭喜恭喜！